<template>
    <div>
        <div class="row">
            <div class="col-3">
                <img style="width:80%;" src="/static/args/tools/arg_oap_logo_d.ico" alt="ARGs-OAP logo" >
            </div>
            <h3 class="col-9">
                <strong>ARGs-OAP:</strong> Online Analysis Pipeline for Anti-biotic Resistance Genes Detection from Meta-genomic Data Using an Integrated Structured ARG-database
            </h3>
        </div>
        
        <blockquote>
            Environmental dissemination of antibiotic resistance genes (ARGs) has become an increasing concern for public health. Metagenomics
            approaches can effectively detect broad profiles of ARGs in environmental samples; however, the detection and subsequent
            classification of ARG-like sequences are time consuming and have been severe obstacles in employing metagenomic methods.
            We sought to accelerate quantification of ARGs in metagenomic data from environmental samples.
        </blockquote>

        <p><a @click="showOnlineAnalysis = true" href="#">Online Analysis</a><a v-if="showOnlineAnalysis" @click="showOnlineAnalysis = false" href="#" style="margin-left:20px;">Collapse</a></p>
        <div v-show="showOnlineAnalysis">
            <div v-if="mode === 1" class="my-tool-wrap">
                <b-form-group label="Please select tool version">
                    <b-form-radio-group v-model="tool.id" name="toolid">
                        <b-form-radio value="__argsoap__">version 1.0</b-form-radio>
                        <b-form-radio value="__argsoap2.0__">versino 2.0</b-form-radio>
                        <b-form-radio value="__argsoap2.2__">version 2.2</b-form-radio>
                    </b-form-radio-group>
                </b-form-group>
                <!-- params -->
                <ParamFile v-model="params.input1" title="Source Fasta File" tip=""></ParamFile>
                <ParamFile v-model="params.input2" title="Meta-data file" tip="The meta data file generated by stage one result"></ParamFile>
                <ParamText v-model="params.input3" title="Column in Metadata" tip="The column in meta data file used to classify samples into groups for PcoA"></ParamText>
                <ParamText v-model="params.input4" title="blastx alignment length cut-off" tip="Hit Length of amino acide in blastx; For 100 reads we chose 25 aa as the default"></ParamText>
                <ParamText v-model="params.input5" title="blastx alignment evalue cut-off" tip="Evalue cut-off to in filter blastx result"></ParamText>
                <ParamText v-model="params.input6" title="blastx alignment identity" tip="Identity cut-off to filter blastx result"></ParamText>
                <ParamText v-model="params.input7" title="institution name" tip="[*] Please enter your institution name here, Please fill a abbr. without gaps in between"></ParamText>
                <ParamText v-model="params.input8" title="Your Email here" tip="[*] Please enter your official email here, no gaps are allowed"></ParamText>
                <ParamText v-model="params.input9" title="Task name for this run" tip="[*] Please enter a unique task name for this runnning, No gaps are allowed in the name"></ParamText>
                <!-- operation -->
                <b-button variant="primary" @click="onExecute">
                    <b-icon icon="check"></b-icon> Execute
                </b-button>
            </div>
            <SuccessTip v-else-if="mode === 2" :name="tool.id" :input="params.input1" :output="[
                'PcoA figure of samples for ARGs abundane matrix normalization against 16S reads number',
                'PcoA figure of samples for ARGs abundance matrix normalization aganist cell number',
                'Subtype, type, and sequence level abundance matrix, normalized against 16S copy numbers',
                'Subtype, type, and sequence level abundance matrix, normalized against cell number',
                'Merge type and subtype ARG abundance table; the value represent number of reads per million reads in each sample'
            ]"></SuccessTip>
            <FailTip v-else-if="mode === 3" :name="tool.id" :msg="'some thing wrong'"></FailTip>
        </div>

        <p><a href="#" @click="showHowToUse = true">How to use</a><a v-if="showHowToUse" @click="showHowToUse = false" href="#" style="margin-left:20px;">Collapse</a></p>
        <div v-show="showHowToUse" class="info-wrap">
            <div>
                <iframe width="935" height="524" src="https://www.youtube.com/embed/PCr1ctXvZPk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            <p>The detailed manual is available <a href="https://github.com/biofuture/Ublastx_stageone">here</a>.</p>
            <ul>
                <li>ARGs-OAP Version 2.0 is now available. For data that has been analyzed with Version 1.0, it is recommend that you do not re-analyze your data using the newer version.</li>
                <li>After migrating to the new server, Stage Two became unstable. If you are receiving error messages (i.e.502/404 error), when uploading the data onto the website, simply refresh the page and select the data type as fasta in the Type (set all) to resolve the error.</li>
            </ul>
        </div>

        <p><a href="#" @click="showDownload = true">Download</a><a v-if="showDownload" @click="showDownload = false" href="#" style="margin-left:20px;">Collapse</a></p>
        <div v-show="showDownload" class="info-wrap">
            <p>Packages are available in Github; and through these links ARGs_OAP version 2.0 <a href="http://smile.hku.hk/SARGs/static/images/Ublastx_stageone2.0.tar.gz">here</a>. ARGs_OAP version 2.2 <a href="http://smile.hku.hk/SARGs/static/images/Ublastx_stageone2.2.tar.gz">here</a>. ARGs_OAP version 2.3 <a href="http://smile.hku.hk/SARGs/static/images/Ublastx_stageone2.3.tar.gz">here</a>.</p>
        </div>

        <p><a href="#" @click="showFAQ = true">FAQ</a><a v-if="showFAQ" @click="showFAQ = false" href="#" style="margin-left:20px;">Collapse</a></p>
        <div v-show="showFAQ" class="info-wrap">
            <p>Stage one:</p>
            <div>
                <div>
                    <p>Q1: Can I directly use .gz files as input?</p>
                    <p>A1: Yes, you can. Please make sure that you have “-z” in your command when running .gz as input files.</p>
                </div>
                <div>
                    <p>Q2: Is it possible to use single fasta file as an input not paired-end reads?</p>
                    <p>A2: For each fasta file, you can generate an empty fasta with the paired name. Then you can follow the pipeline to conduct the analysis process.</p>
                </div>
                <div>
                    <p>Q3: Can contigs be used as input?</p>
                    <p>A3: As this pipeline is designed for short reads (ARGs-OAP) and ORFs (SARGfam), using contigs as input is not well-supported. We will add the annotation and quantification for contigs in future upgrades.</p>
                </div>
                <div>
                    <p>Q4: Cannot execute binary file? I got an error like this: Ublastx_stageone/bin/usearch: cannot execute binary file</p>
                    <p>You should first make Usearch executable by using the command: chmod 755 usearch</p>
                </div>
                <div>
                    <p>Q5: I am wondering if there is any solution with my 32-bit Usearch?</p>
                    <p>A5: Since version 2.3, we have replaced usearch by other tools. Please download version2.3.</p>
                </div>
                <div>
                    <p>Q6: No 16s_hvr_community file in the output? The output after Stage One contains no 16s_hvr_community.txt, 16s_hvr_normal.copy.txt, 16s_hyperout.txt.....Is there anything wrong? Since I still have the extracted .fa and meta_data_online.txt, I can still run Stage Two.</p>
                    <p>A6: Don’t worry. The updated version does not use hyper variable region to get cell numbers. So, there are no such files.</p>
                </div>
            </div>
            <p>Stage two:</p>
            <div>
                <div>
                    <p>Q7: What has happened to the stage two web page http://smile.hku.hk/SARGs? It gives me bad gateway error 502.</p>
                    <p>A7: The server encountered some issues and had to be rebooted, sorry about the inconvenience. You may rerun your analysis.</p>
                </div>
                <div>
                    <p>Q8: I was trying to upload the extracted .fa and meta_data_online.txt to Galaxy ARGs-OAP v2.0, but kept getting error messages "Failed: Bad Gateway (502)" or "Failed: Bad Request (400)". Could you please help?</p>
                    <p>A8: Please simply refresh the page and upload your files again. The server has become unstable after the latest upgrade.</p>
                </div>
                <div>
                    <p>Q9: When I upload the extracted .fa data file, it fails and gives a Gateway timeout error. My fasta file is 1.4 GB. Is there a file size limit?</p>
                    <p>A9: Files should not exceed 2GB, but we suggest 500 MB for each extracted.fa as the uploading process may disconnect due to internet instability or limited upload speed.</p>
                    <ul>
                        <li>Solution 1: Use script divide_extract.fa_meta_data_online.pl to divide dataset (extracted.fa), then run the stage one separately. You need to upload and run each splited files one by one. Alternatively, you may upload them simultaneously in different windows for a batch processing. When you divide the extracted.fa, the meta_data.txt needs to be modified to match extracted.fa after division.</li>
                        <li>Solution 2: Users can try the local version of stage two.</li>
                    </ul>
                </div>
                <div>
                    <p>Q10: If we split the fasta (extracted.fa), do we also have to split the meta_data.txt file to match?</p>
                    <p>A10: Yes, you need to split the meta_data.txt file to match them.</p>
                </div>
                <div>
                    <p>Q11: Would this affect the sample comparison such as the PCoA output later given that these fasta files were run separately with matching meta_data.txt files.</p>
                    <p>A11: No, splitting the files won’t affect the sample comparison. You can generate PCoA by merging all results.</p>
                </div>
            </div>
        </div>

        <p><a href="#" @click="showChangeLog = true">Features Change Log</a><a v-if="showChangeLog" @click="showChangeLog = false" href="#" style="margin-left:20px;">Collapse</a></p>
        <div v-show="showChangeLog" class="info-wrap">
            <p>Version 2.3</p>
            <ul>
                <li>1. no usearch now (if users prefer usearch, please go to previous version). Now, we use minimap2 and diamond.</li>
                <li>2. In stage one, we removed parameter "-s" and "-c"</li>
                <li>3. More importantly, you need to state your Read Length in the meta-data.txt!!!!</li>
            </ul>
            <p>Version 2.2</p>
            <ul>
                <li>Added polymyxin resistance genotypes mcr-1,mcr-1.2,mcr-1.3,mcr-1.4,mcr-1.5,mcr-1.6,mcr-1.7,mcr-1.8,mcr-1.9,mcr-2.1,mcr-2.2,mcr-3,mcr-4,mcr-5,eptA,icr-Mo,icr-Mc</li>
                <li>Added sulfonamide resistance genotypes sul4</li>
                <li>Added quinolone resistance genotypes abaQ</li>
                <li>Added beta-lactam resistance genotypes NDM-1,NDM-9,NDM-10,NDM-11,NDM-12,NDM-13,NDM-16,NDM-14,NDM-15,NDM-17,NDM-20,NDM-18,NDM-19,vim-48,OXA-232</li>
                <li>Added multidrug resistance genotype qacEdelta1</li>
                <li>tetracycline resistance genotypes tetK,tetX,tetX1,tetX2,tetX3,tetX4</li>
                <li>remove usearch (users need to download usearch by themselves,users need to download usearch32 bit by themselves and move it into the folder "bin".) (if users have their own usearch bit64, a suitable SARG.2.2.udb and gg85.udb can be generated follow two steps:firstly, retrieve fasta “usearch_32bit -udb2fasta db.udb -output db.fasta", secondly, generate udb "usearch_64bit -makeudb_ublast db.fasta -output db.udb"), However, we are working in progress to replace usearch by minimap2 and diamond. A follow up update is coming soon after parameter optimization and validation.</li>
                <li>The calculation is copy of ARGs divided by copies of 16S; The copy of ARGs has been changed to Number-of-ARG- like-sequence × Length-of-hit-length / Length-of-ARG-reference-sequence;The previous calculation method of copy of ARGs was Number-of-ARG- like-sequence × Length-of-reads (i.e. 100 or 150) / Length-of-ARG-reference-sequence</li>
            </ul>
            <p>Version 2.0</p>
            <ul>
                <li>SARG database expansion by 3 times</li>
                <li>SARGfam now supplied</li>
                <li>Cell number estimation with universal single-copy marker gene now added</li>
                <li>a -q option now added to perform quality control of raw pair-end fastq files with fastp (https://github.com/OpenGene/fastp)</li>
                <li>Local version of stage two script</li>
                <li>Option -s now added for larger input datasets (useful for users with no 64bit usearch to split big input automatically)</li>
            </ul>
            <p>Version 1.0</p>
            <ul>
                <li>Tools and pipeline functional</li>
            </ul>
        </div>

        <p><a href="#" @click="showHowToCite = true">How To Cite</a><a v-if="showHowToCite" @click="showHowToCite = false" href="#" style="margin-left:20px;">Collapse</a></p>
        <div v-show="showHowToCite" class="info-wrap">
            <p>ARGs_OAP_v1.0 :</p>
            <blockquote>
                Yang Y., Jiang XT, Cai BL, Ma LP, Li B, Zhang AN, Cole JR, Tiedje JM* and Zhang T*. (2016). "ARGs-OAP: Online Analysis Pipeline for Anti-biotic Resistance Genes Detection from Metagenomic Data Using an Integrated Structured ARG-database." Bioinformatics. 32(15):2346-51. doi:10.1093/bioinformatics/btw136.
            </blockquote>
            <p>ARGs_OAP_v2.0 :</p>
            <blockquote>
                Yin, X., X.-T. Jiang, B. Chai, L. Li, Y. Yang, J. R. Cole, J. M. Tiedje and T. Zhang (2018). "ARGs-OAP v2. 0 withan Expanded SARG Database and Hidden Markov Models for Enhancement Characterization and Quantification of Antibiotic Resistance Genes in Environmental Metagenomes." Bioinformatics 1: 8.
            </blockquote>
        </div>

        <p><a href="#" @click="showReportError = true">Report Error</a><a v-if="showReportError" @click="showReportError = false" href="#" style="margin-left:20px;">Collapse</a></p>
        <div v-show="showReportError" class="info-wrap">
            <p>If any issues are encountered, please open an issue at our github repository.</p>
        </div>
    </div>
</template>

<script>
import * as U from './util/index.js'
export default {
    components: {
        SuccessTip: U.SuccessTip,
        FailTip: U.FailTip,
	    ParamText: U.ParamText,
        ParamFile: U.ParamFile,
        ParamSelect: U.ParamSelect
  	},
    data() {
        return {
            mode: 1, // 1表单，2成功提示，3失败提示
            showOnlineAnalysis: false,
            showHowToUse: false,
            showFAQ: false,
            showChangeLog: false,
            showDownload: false,
            showHowToCite: false,
            showReportError: false,
            tool: {
                id: '__argsoap__',
                version: '1.0.0'
            },
            opts: [
                { text: 'Item 1', value: 'first' },
                { text: 'Item 2', value: 'second' }
            ],
            params: {
                input1: '',
                input2: '',
                input3: '',
                input4: '',
                input5: '',
                input6: '',
                input7: '',
                input8: '',
                input9: ''
            }
        };
    },
    created() {
        this.mode = 1
    },
    methods: {
        onExecute() {
            this.$emit('exec', this.tool, this.params, (res) => {
                this.mode = 2
            });
        }
    }
}
</script>

<style scoped src="./util/index.css"></style>
