<template>
    <div>
        <div class="row">
            <div class="col-3">
                <img style="width:90%;" src="/static/args/tools/arg_oap_logo_d.ico" alt="ARGs-OAP logo" >
            </div>
            <h3 class="col-9">
                <strong>ARGs-OAP:</strong> Online Analysis Pipeline for Anti-biotic Resistance Genes Detection from Meta-genomic Data Using an Integrated Structured ARG-database
            </h3>
        </div>
        
        <blockquote>
            Environmental dissemination of antibiotic resistance genes (ARGs) has become an increasing concern for public health. Metagenomics
            approaches can effectively detect broad profiles of ARGs in environmental samples; however, the detection and subsequent
            classification of ARG-like sequences are time consuming and have been severe obstacles in employing metagenomic methods.
            We sought to accelerate quantification of ARGs in metagenomic data from environmental samples.
        </blockquote>

        <p><a @click="onOpen" href="#">Online Analysis</a></p>
        <p><a href="#argoap-how-to-use">How to use</a></p>
        <p><a href="#argoap-downloads">Download</a></p>
        <p><a href="#argoap-faq">FAQ</a></p>
        <p><a href="#argoap-features-change-log">Features Change Log</a></p>
        <p><a href="#argoap-how-to-cite">How To Cite</a></p>
        <p><a href="#argoap-report-error">Report Error</a></p>

        <!-- online analysis modal -->
        <b-modal v-model="modalShow" static no-enforce-focus hide-footer>
            <template v-slot:modal-header><h4 class="title" tabindex="0">Online Analysis</h4></template>
            <div class="my-tool-wrap">
                <!-- params -->
                <ParamFile v-model="params.input" :folder="true" title="ARG profile" tip="The mothertable is generated by arg-oap, should be abundance in sequence level, and normalized by 16S copy numbers"></ParamFile>
                <ParamSelect v-model="params.suffix" :options="opts" title="institution name" tip="[*] Please enter your institution name here, Please fill a abbr. without gaps in between"></ParamSelect>

                <b-button variant="primary" @click="onExecute">
                    <b-icon icon="check"></b-icon> Execute
                </b-button>
            </div>
        </b-modal>
    </div>
</template>

<script>
import * as U from './util/index.js'
export default {
    components: {
	    ParamText: U.ParamText,
        ParamFile: U.ParamFile,
        ParamSelect: U.ParamSelect
  	},
    data() {
        return {
            modalShow: false,
            tool: {
                id: '__args_index__',
                version: '1.0.0'
            },
            opts: [
                { text: '.txt', value: '.txt' },
                { text: '.gbk', value: '.gbk' }
            ],
            params: {
                input: '',
                suffix: ''
            }
        };
    },
    methods: {
        onOpen(evt) {
            this.modalShow = true;
        },
        onExecute() {
            this.$emit('exec', this.tool, this.params);
        }
    }
}
</script>

<style scoped>
.my-tool-wrap {
    min-height: 480px;
}
</style>