<template>
    <div>
        <h1>This is DEMO tool for test</h1>
        <p><a @click="showOnlineAnalysis = true" href="#">Online Analysis</a><a v-if="showOnlineAnalysis" @click="showOnlineAnalysis = false" href="#" style="margin-left:20px;">Collapse</a></p>
        <div v-show="showOnlineAnalysis" class="my-tool-wrap">
            <!-- params -->
            <!-- <ParamFile v-model="params.input1" :folder="true" title="ARG profile" tip="The mothertable is generated by arg-oap, should be abundance in sequence level, and normalized by 16S copy numbers"></ParamFile>
            <ParamFile v-model="params.input2" title="ARG profile" tip="The mothertable is generated by arg-oap, should be abundance in sequence level, and normalized by 16S copy numbers"></ParamFile>
            <ParamSelect v-model="params.input3" :options="opts" title="institution name" tip="[*] Please enter your institution name here, Please fill a abbr. without gaps in between"></ParamSelect>
            <ParamText v-model="params.input4" title="Your Email here" tip="[*] Please enter your official email here, no gaps are allowed"></ParamText>
            <ParamText v-model="params.input5" title="Task name for this run" tip="[*] Please enter a unique task name for this runnning, No gaps are allowed in the name"></ParamText> -->

            <ParamFile v-model="params.input" :folder="true" title="Param 1: Folder" tip="Please select a folder for test"></ParamFile>
            <ParamSelect v-model="params.suffix" :options="opts" title="Param 2: File Suffix" tip="[*] Please select the file suffix"></ParamSelect>
            <!-- operation -->
            <b-button variant="primary" @click="onExecute">
                <b-icon icon="check"></b-icon> Execute
            </b-button>
        </div>
    </div>
</template>

<script>
import * as U from './util/index.js'
export default {
    components: {
	    ParamText: U.ParamText,
        ParamFile: U.ParamFile,
        ParamSelect: U.ParamSelect
  	},
    data() {
        return {
            showOnlineAnalysis: false,
            tool: {
                id: '__args_index__',
                version: '1.0.0'
            },
            opts: [
                { text: '.txt', value: '.txt' },
                { text: '.gbk', value: '.gbk' }
            ],
            params: {
                input: '',
                suffix: ''
            }
        };
    },
    methods: {
        onExecute() {
            this.$emit('exec', this.tool, this.params);
        }
    }
}
</script>

<style scoped>
.my-tool-wrap {
    border: 1px solid #ccc;
    border-radius: 5px;
    padding: 15px;
    margin: 15px 0;
}
</style>