<template>
    <div>
        <h3>Microbial Source Tracking (MST)</h3>
        
        <blockquote>
            Microbial Source Tracking is a source-tracking platform using machine-learning classification with ARG abundance profiles. In other words, it precisely tracks antibiotic resistance gene pollution from different sources when your samples are related to human feces, animal feces, wastewater treatment plants, natural environments. This is a novel application of your high-throughput sequencing dataset. The developed source-tracking platform when coupling with proper experiment design and efficient metagenomic analysis tools will have significant implications for assessing AMR pollution. Following predicted source contribution status, risk ranking of different sources in ARG dissemination will be possible, thereby paving the way for establishing priority in mitigating ARG spread and designing effective control strategies.
        </blockquote>

        <p><a @click="showOnlineAnalysis = true" href="#">Online Analysis</a><a v-if="showOnlineAnalysis" @click="showOnlineAnalysis = false" href="#" style="margin-left:20px;">Collapse</a></p>
        <div v-show="showOnlineAnalysis" class="my-tool-wrap">
            <!-- params -->
            <ParamFile v-model="params.input1" title="ARG profile" tip="The mothertable is generated by arg-oap, should be abundance in sequence level, and normalized by 16S copy numbers"></ParamFile>
            <ParamText v-model="params.input2" title="institution name" tip="[*] Please enter your institution name here, Please fill a abbr. without gaps in between"></ParamText>
            <ParamText v-model="params.input3" title="Your Email here" tip="[*] Please enter your official email here, no gaps are allowed"></ParamText>
            <ParamText v-model="params.input4" title="Task name for this run" tip="[*] Please enter a unique task name for this runnning, No gaps are allowed in the name"></ParamText>
            <!-- operation -->
            <b-button variant="primary" @click="onExecute">
                <b-icon icon="check"></b-icon> Execute
            </b-button>
        </div>

        <p><a href="#" @click="showHowToUse = true">How to use</a><a v-if="showHowToUse" @click="showHowToUse = false" href="#" style="margin-left:20px;">Collapse</a></p>
        <div v-show="showHowToUse" class="info-wrap">
            <p>To conduct microbial source tracking, users should firstly conduct ARG Analysis Pipeline (version 1) to get the ARG abundance profile. From the abundance mothertable which normalized abundance against 16S copies, extract the matrix for sequence/gene level. Then upload it to the online Galaxy for tracking ARG from different sources.</p>

            <p>Input file:</p>
            <p>A table with sample names as column name, and ARG sequence/gene name as row name (this is the default format of output table in ARG sequence/gene level after running ARGs-OAP)</p>

            <p>Output files:</p>

            <p>A table summaries predicted proportion standard deviation of these 10 separate runs.</p>
            <p>A table summaries source-tracking results with sample names as row name. Column names are “feces_animal→feces_human→natural→wwtp→Unknown”. Results are predicted proportions from five sources in each sample. The values are average values after 10 times separate run.</p>
            <p>If your samples are not so related to human feces, animal feces, wastewater treatment plants and natural environments, we can not guarantee the prediction accuracy, because the model was developed and validated with these types of samples as training dataset.</p>
        </div>

        <p><a href="#" @click="showHowToCite = true">How To Cite</a><a v-if="showHowToCite" @click="showHowToCite = false" href="#" style="margin-left:20px;">Collapse</a></p>
        <div v-show="showHowToCite" class="info-wrap">
            <blockquote>
                Li, Li-Guan, Yin, Xixaole and Zhang Tong*. Tracking antibiotic resistance gene pollution from different sources using machine-learning classification. Microbiome 2018;6(1):93. DOI:10.1186/s40168-018-0480-x
            </blockquote>
        </div>

        <p><a href="#" @click="showContacts = true">Contacts</a><a v-if="showContacts" @click="showContacts = false" href="#" style="margin-left:20px;">Collapse</a></p>
        <div v-show="showContacts" class="info-wrap">
            <p>LiGuan Li: leeliguan@gmail.com</p>
            <p>Xiaole Yin: yinlele99@gmail.com</p>
        </div>
    </div>
</template>

<script>
import * as U from './util/index.js'
export default {
    components: {
	    ParamText: U.ParamText,
        ParamFile: U.ParamFile,
        ParamSelect: U.ParamSelect
  	},
    data() {
        return {
            showOnlineAnalysis: false,
            showHowToUse: false,
            showHowToCite: false,
            showContacts: false,
            tool: {
                id: '__mst__',
                version: '1.0.0'
            },
            params: {
                input1: '',
                input2: '',
                input3: '',
                input4: ''
            }
        };
    },
    methods: {
        onExecute() {
            this.$emit('exec', this.tool, this.params);
        }
    }
}
</script>

<style scoped>
blockquote {
    border-left: 5px solid #ee6e73;
    padding-left: 20px;
    margin: 20px 0;
}
.my-tool-wrap {
    border: 1px solid #ccc;
    border-radius: 5px;
    padding: 15px;
    margin: 15px 0;
}
.info-wrap {
    border: 1px solid #ccc;
    border-radius: 5px;
    padding: 15px;
    margin: 15px 0;
}
</style>